setup.py

Currently if package is installed in non-development mode it will miss template files.
This commit fixes this.

fix setup.py to include theme

---

.travis.yml
README.md
ckanext/pages/plugin.py
ckanext/pages/tests/test_logic.py
ckanext/pages/theme/templates_main/ckanext_pages/group_page.html
ckanext/pages/theme/templates_main/ckanext_pages/organization_page.html
ckanext/pages/theme/templates_main/ckanext_pages/page.html

In CKAN 2.3 (specifically with [PR #1774](https://github.com/ckan/ckan/pull/1774)) the `render_markdown` method got a new parameter `allow_html` which prevents the filtering of HTML in the content.
I want to enable this feature in ckanext-pages and suggest a new config option to control that:
```
ckanext.pages.allow_html = True
```
By default it is `False`.
To prevent having to call this explicitly in the template (e.g. `h.render_markdown(content, allow_html=True)`), I added a new helper function called `render_content`. That might be useful in the future, if the API of `render_markdown` changes again, or different kind of renderings should be supported.
To keep the plugin independent of the CKAN version, `render_content` tries to call the `render_markdown` with the new `allow_html` named …

Add option to allow HTML when rendering markdown

---

ckanext/pages/actions.py
ckanext/pages/controller.py
ckanext/pages/plugin.py
ckanext/pages/theme/templates_main/ckanext_pages/snippets/pages_list.html

I just closed #29, because there are actually a few more bugs I discovered just yesterday.
Wrong argument: in controller.py line 269.
datetime in json: in action.py, _page_list method, datetime is put directly inside a json file to be returned. Datetime object is not json serializable, so it is a better idea to convert it first.
API broken: all GET methods that do not specify side_effect_free to true will throw an exception in CKAN, so I propose to add decorator for all the GET methods.

fixes a few things. wrong argument, datetime in json, API broken

---

ckanext/pages/db.py

This should address #27 by adding the (default False) kwarg "extend_existing=True" to the init_db() function of db.py.
Tested on datacats ckan "latest" (2.5a ckan master).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ckan/ckanext-pages/28)

added kwarg extend_existing=True to init_db()

---

ckanext/pages/actions.py

Currently uploading pictures defaults to using local storage path only. Since 2.5 the ckan.lib.uploader.get_uploader method allows to use an extended uploader, for example using ckanext-s3filestore.

Use get_uploader if ckan version is 2.5 or up

---

setup.py

Fixes plugin's setup.py namespace_packages to match the updated setup.py paster template. Fixes the issue mentioned in e.g. here: https://github.com/ckan/ckan/issues/2893

Fix namespace_packages

---

.travis.yml
bin/travis-build.bash

Fixes #61 and adds 2.7 to the list of CKAN versions tested on Travis.

[#61] Wrong CKAN version on Travis

---

ckanext/pages/controller.py

Fixes #60. 
Parts of code passed the result of `url_for` to `redirect_to`, which resulted in the localization code being added twice to the URL.

[#60] Fix wrong redirects for localized URLs

---

ckanext/pages/plugin.py
ckanext/pages/tests/test_logic.py
test.ini

Fixes #58 by replacing the version check using `h.ckan_version` with `toolkit.check_ckan_version`.

[#58] Fix CKAN version check on older versions

---

ckanext/pages/controller.py
ckanext/pages/theme/templates_main/ckanext_pages/base_form.html

Fixes #53.
The delete buttons on group and organization pages had incorrect URLs. In addition, the controller for deleting group pages was completely missing.

[#53] Cannot delete org and group pages

---

LICENSE
README.md
setup.py

Adds a `LICENSE` file and a corresponding notice in `README.md` for the AGPL v3.0 license which is used for all CKAN extensions.
@amercader Please let me know if there is anything else that should be mentioned regarding license/copyright.

[#73] Document the project's license (AGPL v3.0)

---

bin/travis-build.bash
ckanext/pages/controller.py
ckanext/pages/tests/test_logic.py
ckanext/pages/theme/templates_main/ckanext_pages/page.html
test.ini

If lxml is enabled, the `_inject_views_into_page` method of the controller does some tweaking of the HTML tree. If the content passed is a text snippet (like 99.99% of the markdown content passed) it will wrap it on `<p>` tags (or if the snippet starts with a `<p>` tag, with a `<div>` tag). This will cause the snippet to not be properly rendered.

Remove extraneous tags added by lxml that prevent proper rendering

---

ckanext/pages/actions.py
ckanext/pages/auth.py
ckanext/pages/controller.py
ckanext/pages/theme/templates_main/ckanext_pages/base_form.html
ckanext/pages/theme/templates_main/ckanext_pages/group_page.html
ckanext/pages/theme/templates_main/ckanext_pages/organization_page.html

Currently, page edit form for both organization and group pages calls `pages_update` function, that requires sysadmin account.  As a result, organization admins(not sysadmins) will be logged out after an attempt to update the organization's page.
This PR updates permission checks as well as fixes few small problems(for example, group/org edit auth checks were returning boolean instead of dict in form `{'success': boolean}`)

Fix group/org pages update permissions

---

ckanext/pages/plugin.py

This PR fixes issue #82.
It handles multiple routing structures used by different versions of ckan, to ensure that the extensions config can still disable main menu items.

Fix issue 82

---

ckanext/pages/theme/public/ckedit.js

This PR fixes a bug that caused styles to not being properly displayed in ckeditor when editing pages/blogs. The following gif shows the behavior to fix.
To solve it I added a new config based on the solution proposed [here.](https://stackoverflow.com/a/18756230)

Adding configuration for CKEditor to render styles in the editor

---

ckanext/pages/controller.py

The dictization_functions only sets error keys for missing or validation error in the form. If there is an error not related to the form, it neither gets displayed in the browser neither on the terminal.
The issue is that the pages extension self redirects to the edit pages link in the case of the exception rather than raising it. It redirects to the edit page with an error dictionary that gets displayed in the browser similar to when you try to add a page without a title, it will not raise an exception in the terminal although it will show the error in the browser like 'Missing Value'.
This PR will add a flash message of the error summary at the top of the page to get notified of the occurrence of an error.

Adding flash_error message in case of missing values

---

ckanext/pages/actions.py

This fixes situations where some IUploader implementations may return an absolute HTTP URL as the `image_url` after uploading. This changes the logic to only prefix URLs with the static URL if they are not already absolute.

Do not prefix absolute HTTP URLs of uploaded image

---

ckanext/pages/theme/templates_main/ckanext_pages/blog.html

Fixes an issue when you try to view a blog and you have more the one blogs created on the portal. 
This is happens on CKAN 2.9+.

Fix for blog view issue if more then one blog is created on CKAN 2.9

---

.github/workflows/test.yml
README.md
ckanext/pages/actions.py
ckanext/pages/auth.py
ckanext/pages/blueprint.py
ckanext/pages/cli.py
ckanext/pages/commands.py
ckanext/pages/db.py
ckanext/pages/plugin/__init__.py
ckanext/pages/plugin/flask_plugin.py
ckanext/pages/plugin/pylons_plugin.py
ckanext/pages/tests/fixtures.py
ckanext/pages/tests/test_logic.py
ckanext/pages/utils.py
setup.py

Fixes #106
Database initialization code is executed on all actions and auth functions which probably leads to errors on multi-thread environments. This PR moves the initialization code to cli and is more inline with the other extensions and good conventions. Database initialization is also somewhat cleaned as raw sql lines were removed as sqlalchemy mapper already existed.
Also flake8 violations are fixed.

Move database initialization to cli

---

ckanext/pages/actions.py

This PR implements an error handling to the `page_upload` action so CKEditor can render a proper message to the user:

Upgrade uploads UX

---

.github/workflows/test.yml
ckanext/pages/textbox/templates/textbox_form.html
ckanext/pages/theme/templates_main/ckanext_pages/base_form.html

Helper `h.url(...)` has been deprecated in favor of `h.url_for(...)`.
Current codebase will throw an error when running it in CKAN 2.10.

Replace deprecated h.url() helper.

---

ckanext/pages/utils.py

Problem: When the page is successfully deleted, a user is redirected to the `pages.index` endpoint, which was renamed recently to `pages.pages_index`
Fix: Update redirect and use the current name of the endpoint.

fix: wrong endpoint name for redirect after page removal

---

README.md
ckanext/pages/actions.py
ckanext/pages/blueprint.py
ckanext/pages/db.py
ckanext/pages/migration/pages/versions/1725892d1d94_create_revisions_table.py
ckanext/pages/plugin.py
ckanext/pages/tests/test_action.py
ckanext/pages/tests/test_logic.py
ckanext/pages/theme/templates_main/ckanext_pages/blog.html
ckanext/pages/theme/templates_main/ckanext_pages/blog_revisions.html
ckanext/pages/theme/templates_main/ckanext_pages/blog_revisions_preview.html
ckanext/pages/theme/templates_main/ckanext_pages/page.html
ckanext/pages/theme/templates_main/ckanext_pages/page_revisions.html
ckanext/pages/theme/templates_main/ckanext_pages/page_revisions_preview.html
ckanext/pages/utils.py

Hi @amercader and  @wardi 
With this PR I want to add Revision feature to the Pages and Blog HTML content.
It is a quite straightforward feature that adds and ability to Restore previous Content state in case if something went wrong while saving current version.
By default it creates only 3 versions, while can be increased with **ckanext.pages.revisions_limit** config setting.
It shouldn't effect old pages that were created before the Revisions logic update and the first Revision for those Pages/Blogs can be create by re-saving the current version.
It required DB upgrade after pulling.
Please review, test this and let me know if any adjustments are needed.

Pages revisions feature

---

ckanext/pages/plugin.py

Since #102 looks inactive for quite some time we created a new pull request addressing the issue.
This solves the behavior if `ckan.root_path` is set ( Fixes #98 ).

Fix url building if root_path is set
